collections:
  - name: community.kubernetes
    version: 1.0.0
    source: https://galaxy.ansible.com

  - name: community.crypto.openssh_keypair
    version: 2.9.0
    source: https://galaxy.ansible.com
