download_url: https://galaxy.ansible.com/download/community-kubernetes-2.0.1.tar.gz
format_version: 1.0.0
name: kubernetes
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.1
version_url: https://galaxy.ansible.com/api/v2/collections/community/kubernetes/versions/2.0.1/
