---
- name: '[OCP4-AUTO-INSTALL] Deploy an OpenShift Logging'
  hosts: localhost
  connection: local
  vars_files:
    - vars/modules.yml
    - vars/vars.yml
    - vault/vault.yml
  collections:
    - community.kubernetes
    - community.crypto
    - ansible.posix
    - community.general
    
  tasks:

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][LOGGING] Install and configure Logging'
      include_role:
        name: "ocp4-post-logging"
      when:
        - install_logging == True
