---
- name: '[OCP4-AUTO-INSTALL] Deploy an Openshift4 cluster'
  hosts: localhost
  connection: local
  vars_files:
    - vars/vars.yml
    - vault/vault.yml
  tasks:
    - name: '[OCP4-AUTO-INSTALL][PREREQS] Prerequisites for the installation'
      include_role:
        name: "common"
      when:
        - only_post_install != True

    - name: '[OCP4-AUTO-INSTALL][INSTALL] Installation of the OCP4 Cluster'
      include_role:
        name: "ocp4-install-vsphere"
      when:
        - only_post_install != True