---
- name: '[OCP4-AUTO-INSTALL] Deploy an Openshift4 cluster'
  hosts: localhost
  connection: local
  vars_files:
    - vars/modules.yml
    - vars/vars.yml
    - vault/vault.yml
  collections:
    - community.kubernetes
    - community.crypto
    - ansible.posix
    - community.general
    
  tasks:
    - name: '[OCP4-AUTO-INSTALL][PREREQS] Prerequisites for the installation'
      include_role:
        name: "common"
      when:
        - pre_reqs_install == True

    - name: '[OCP4-AUTO-INSTALL][PREREQS] Prerequisites for the installation'
      include_role:
        name: "ocp4-pre-install"
      when:
        - check_pre_reqs == True

    - name: '[OCP4-AUTO-INSTALL][INSTALL] Installation of the OCP4 Cluster'
      include_role:
        name: "ocp4-install-vsphere"
      when:
        - only_post_install == True

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][INFRA-NODES] Deploy and configure Infra Nodes'
      include_role:
        name: "ocp4-post-infra-nodes"
      when:
        - infra_post_install == True

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][LOGGING] Install and configure Logging'
      include_role:
        name: "ocp4-post-logging"
      when:
        - install_logging == True

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][ODF] Install and configure ODF'
      include_role:
        name: "ocp4-post-odf"
      when:
        - install_odf == True

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][BKP-ETCD] Configure Backup ETCD'
      include_role:
        name: "ocp4-post-bkp-etcd"
      when:
        - bkp_etcd_post_install == True

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][TIME] Configure Timezone and Chrony'
      include_role:
        name: "ocp4-post-timezone-chrony"
      when:
        - set_timezone_chrony == True

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][AUTH] Configure Authentication'
      include_role:
        name: "ocp4-post-auth"
      when:
        - set_auth == True

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL] Backup Files'
      include_role:
        name: "ocp4-post-backup-files"
      when:
        - backup_files == True