---
- name: '[OCP4-AUTO-INSTALL] Deploy an Openshift4 cluster'
  hosts: localhost
  connection: local
  vars_files:
    - vars/vars.yml
    - vault/vault.yml
  tasks:
    - name: '[OCP4-AUTO-INSTALL][PREREQS] Prerequisites for the installation'
      include_role:
        name: "common"
      when:
        - pre_reqs_install == True

    - name: '[OCP4-AUTO-INSTALL][INSTALL] Installation of the OCP4 Cluster'
      include_role:
        name: "ocp4-install-vsphere"
      when:
        - only_post_install == True

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][INFRA-NODES] Deploy and configure Infra Nodes'
      include_role:
        name: "ocp4-post-infra-nodes"
      when:
        - infra_post_install == True
        - infra_nodes is defined
        - infra_nodes | bool

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][LOGGING] Install and configure Logging'
      include_role:
        name: "ocp4-post-logging"
      when:
        - install_logging == True
        - logging is defined
        - logging | bool