- name: '[POSTINSTALL][INFRA-NODES] Configure Image Registry Node Selector and Tolerations'
  when: 
  - ocp4_workload_machinesets_cluster_version is version_compare('4.10', '>')
  - configure_image_registry == True
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    merge_type:
    - merge
    definition: "{{ lookup('template', 'image-registry.j2') }}"
