---

- name: '[POSTINSTALL][INFRA-NODES] Grab some global cluster trivia for git to use'
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: infradata

- name: '[POSTINSTALL][INFRA-NODES] Deploy Infra Nodes MachineSet'
  vars:
    node_labels:
    - "{{ infra_label }}"
    name_identifier: "{{ infra_label }}"
  include_role:
    name: ocp4-post-machinesets

#- name: '[POSTINSTALL][INFRA-NODES] Wait for Infra Nodes to be available'
#  k8s_info:
#    kubeconfig: "{{ kubeconfig }}"
#    api_version: v1
#    kind: Node
#    label_selectors:
#    - node-role.kubernetes.io/infra =
#  register: r_infra_nodes
#  until:
#  - r_infra_nodes.resources | length | int == infra_node_replicas | int
#  delay: 30
#  retries: 15
#
#- name: '[POSTINSTALL][INFRA-NODES] Get ClusterVersion'
#  k8s_info:
#    kubeconfig: "{{ kubeconfig }}"
#    api_version: config.openshift.io/v1
#    kind: ClusterVersion
#    name: version
#  register: r_cluster_version
#
#- name: '[POSTINSTALL][INFRA-NODES] Set ocp4_workload_machinesets_cluster_version fact'
#  set_fact:
#    ocp4_workload_machinesets_cluster_version: "{{ r_cluster_version.resources[0].status.history[0].version }}"
#
#- name: '[POSTINSTALL][INFRA-NODES] Configure Ingress Controllers and Image Registry'
#  when: ocp4_workload_machinesets_cluster_version is version_compare('4.5', '<')
#  k8s:
#    kubeconfig: "{{ kubeconfig }}"
#    state: present
#    merge_type:
#    - merge
#    definition: "{{ lookup('template', '{{ item }}') }}"
#  loop:
#  - ./templates/ingress-controller.j2
#  - ./templates/image-registry.j2