---

- name: '[POSTINSTALL][LOGGING] Setup Logging configuration'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'templates/logging-crd.yml') }}"

- name: '[POSTINSTALL][LOGGING] Wait for operator to be ready'
  pause:
    seconds: 90

- name: '[POSTINSTALL][LOGGING] Wait for OpenShift Logging to be available'
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Pod
    wait: yes
    namespace: openshift-logging
    field_selectors:
      - status.phase=Running
    validate_certs: false