---
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance" 
  namespace: "openshift-logging"
spec:
  managementState: "Managed"  
  logStore:
    type: "elasticsearch"  
    retentionPolicy: 
      application:
        maxAge: "{{ app_max_age }}"
      infra:
        maxAge: "{{ infra_max_age }}"
      audit:
        maxAge: "{{ audit_max_age }}"
    elasticsearch:
      nodeCount: {{ es_nodeCount }} 
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved   
      storage:
        storageClassName: "{{ es_storageClass }}" 
        size: "{{ es_diskSize }}"
      resources: 
        limits:
          memory: "16Gi"
        requests:
          memory: "16Gi"
      proxy: 
        resources:
          limits:
            memory: 256Mi
          requests:
             memory: 256Mi
      redundancyPolicy: "{{ es_redundancy }}"
  visualization:
    type: "kibana"  
    kibana:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      replicas: 1
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
  collection:
     logs:
      fluentd:
        tolerations:
          - operator: Exists
      type: fluentd