---

- name: '[POSTINSTALL] Create htpasswd Files'
  community.general.htpasswd:
    path: "{{ files_path }}/htpasswd.users"
    name: admin
    password: "{{ htpasswd_pass }}"
    crypt_scheme: md5_crypt
  when: config_htpasswd == True
