---

- name: '[POSTINSTALL] Create htpasswd Files'
  community.general.htpasswd:
    path: "{{ files_path }}/users.htpasswd"
    name: admin
    password: "{{ htpasswd_pass }}"
    crypt_scheme: md5_crypt
  when: config_htpasswd == True

- name: '[POSTINSTALL] Create Secret htpasswd Files'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: htpass-secret
        namespace: openshift-config
      data:
        htpasswd: "{{ lookup('file', '{{ files_path }}/users.htpasswd') | b64encode }}"
    validate_certs: false
    validate:
      fail_on_error: yes
  when: config_htpasswd == True