---

- name: '[POSTINSTALL] Create htpasswd Files'
  community.general.htpasswd:
    path: "{{ files_path }}/users.htpasswd"
    name: "{{ htpasswd_user }}"
    password: "{{ htpasswd_pass }}"
    crypt_scheme: md5_crypt
  when: config_htpasswd == True

- name: '[POSTINSTALL] Create Secret htpasswd Files'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: htpass-secret
        namespace: openshift-config
      data:
        htpasswd: "{{ lookup('file', '{{ files_path }}/users.htpasswd') | b64encode }}"
    validate_certs: false
    validate:
      fail_on_error: yes
  when: config_htpasswd == True

- name: '[POSTINSTALL] Apply Htpasswd Oauth'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
   merge_type:
    - merge
    definition: "{{ lookup('template', 'oauth-htpasswd.j2') }}"
  when: config_htpasswd == True

- name: '[POSTINSTALL] Apply Cluster Admin User Htpasswd'
  shell:
    cmd: "{{ files_path }}/oc --kubeconfig {{ kubeconfig }} --insecure-skip-tls-verify adm policy add-cluster-role-to-user cluster-admin {{ htpasswd_user }}"
  when: config_htpasswd == True