---
# tasks file for roles/common

- name: '[COMMON] Create a directory for the installation'
  file:
    name: "{{ user_path }}"
    state: directory

- name: '[COMMON] Create a directory for the deploy files'
  file:
    name: "{{ deploy_path }}"
    state: directory

- name: '[COMMON] Create a directory for the binary files'
  file:
    name: "{{ files_path }}"
    state: directory

- name: '[COMMON] Create a directory for the backup files'
  file:
    name: "{{ bkp_path }}"
    state: directory

- name: '[INSTALL_CONFIG] Create bin directory'
  file:
    path: "{{ user_path }}/.ssh"
    state: directory

- name: '[INSTALL_CONFIG] Generate SSH keys'
  openssh_keypair:
    type: ed25519
    path: "{{ user_path }}/.ssh/id_rsa"

- name: '[INSTALL_CONFIG] Slurp public key'
  slurp:
    path: "{{ user_path }}/.ssh/id_rsa.pub"
  register: idrsapub

- name: '[INSTALL_CONFIG] [PREREQS] Copy python prerequisites file'
  copy:
    src: ./requirements.txt
    dest: "{{ user_path }}/requirements.txt"
    
- name: '[INSTALL_CONFIG] [PREREQS] Install python prerequisites'
  pip:
    requirements: "{{ user_path }}/requirements.txt"