---
# tasks file for roles/common

- name: '[COMMON] Create a directory for the installation'
  file:
    name: "{{ user_path }}"
    state: directory

- name: '[INSTALL_CONFIG] Slurp public key'
  slurp:
    path: "{{ user_path }}/.ssh/id_rsa.pub"
  register: idrsapub