---

- name: '[INSTALL_CONFIG] Generate config install-config.yaml'
  template:
    src: install-config.yaml.j2
    dest: "{{ deploy_path }}/install-config.yaml"

- name: '[INSTALL_CONFIG] Make a copy of the cluster install config for backup purposes'
  copy:
    src: "{{ deploy_path }}/install-config.yaml"
    dest: "{{ deploy_path }}/install-config.yaml.bck"