---

    - name: '[INSTALL] Installing Openshift Cluster...'
      shell: 
        cmd: "{{ user_path }}/openshift-install create cluster --dir {{ user_path }} --log-level debug"
      async: 21000
      poll: 0
      register: install
    
    - name: '[INSTALL] Check on an async task'
      async_status:
        jid: "{{ install.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 120
      delay: 30
    
    - name: '[INSTALL] Output Install Log...'
      debug:
         var: install.stdout_lines
    
    - name: '[INSTALL] Gzip Install files'
      archive:
        path: "{{ user_path }}/{{ item }}"
        dest: "{{ tower_path }}/{{ cluster_name }}-{{ ocp_cluster }}-install.gz"
        format: gz
      loop:
        - .openshift_install_state.json
        - .openshift_install.log
        - terraform.tfvars.json
        - terraform.tfstate
        - metadata.json
        - terraform.aws.auto.tfvars.json
        - openshift-install
      when:
        - tower_used is defined
        - tower_used | bool